sonar.projectKey=my_project_key
sonar.organization=my_organization
sonar.sources=src
sonar.exclusions=**/*.test.js,**/node_modules/**,**/*.spec.js,dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
